### ISSUE TITLE
Shadowing doesn't work as expected

### ISSUE THREAD

**Issue by mrkgnao** [lexi-lambda/higher-rank#3] opened 2017-06-03 16:39 UTC
Here's a minimal example:

```
((\x -> (\x -> x)) ())
*** Exception: ctxSolution: internal error — multiple types for variable: [CtxAssump (MkEVar {unEVar = "x"}) (TEVar (MkTEVar {unTEVar = "a1"})),CtxAssump (MkEVar {unEVar = "x"}) (TEVar (MkTEVar {unTEVar = "a3"}))]
````

**Comment by lexi-lambda** [comment] 2017-06-03 16:48
This is a duplicate of #2.

**Closed as completed by lexi-lambda** 2017-06-03 16:48 UTC
